name: Deploy Discord Bot

on:
  push:
    branches: [counting]
  pull_request:
    branches: [counting]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/discord-bot
            git remote set-url origin https://apikdech:${{ secrets.GH_TOKEN }}@github.com/apikdech/discord-selfbot.git
            git pull origin counting
            source venv/bin/activate
            pip install -r requirements.txt
            # Update service file and reload systemd
            sudo cp deployment/discord-bot.service /etc/systemd/system/
            sudo systemctl daemon-reload
            sudo systemctl restart discord-bot.service
